/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e9b968882f82d390e7778d0
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ContactsService } from '../../services/contacts.service';
// Import Models
import { Contacts } from '../../domain/new-app_db/contacts';

// START - USED SERVICES
/**
* contactsService.delete
*	@description CRUD ACTION delete
*
* contactsService.list
*	@description CRUD ACTION list
*	@returns ARRAY OF contacts
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Contacts
 * @class ContactsListComponent
 */
@Component({
    selector: 'app-contacts-list',
    templateUrl: './contacts-list.component.html',
    styleUrls: ['./contacts-list.component.css']
})
export class ContactsListComponent implements OnInit {
    list: Contacts[];
    search: any = {};
    idSelected: string;
    constructor(
        private contactsService: ContactsService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.contactsService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Contacts to remove
     *
     * @param {string} id Id of the Contacts to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Contacts
     */
    deleteItem() {
        this.contactsService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
