/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e9b968882f82d390e7778d0
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE contactsBaseService PLEASE EDIT ../contacts.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Contacts } from '../../domain/new-app_db/contacts';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../contacts.service.ts
 */

/*
 * SCHEMA DB contacts
 *
	{
		email: {
			type: 'String'
		},
		fName: {
			type: 'String',
			required : true
		},
		facebook: {
			type: 'String'
		},
		lName: {
			type: 'String'
		},
		phone: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class ContactsBaseService {

    contextUrl: string = environment.endpoint + '/contacts';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * contactsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Contacts): Observable<Contacts> {
        return this.http
            .post<Contacts>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * contactsService.delete
    *   @description CRUD ACTION delete
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * contactsService.findByemail
    *   @description CRUD ACTION findByemail
    *
    */
    findByEmail(id: string): Observable<Contacts[]> {
        return this.http
            .get<Contacts[]>(this.contextUrl + '/findByemail/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * contactsService.get
    *   @description CRUD ACTION get
    *   @returns contacts
    *
    */
    get(id: string): Observable<Contacts> {
        return this.http
            .get<Contacts>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * contactsService.list
    *   @description CRUD ACTION list
    *   @returns ARRAY OF contacts
    *
    */
    list(): Observable<Contacts[]> {
        return this.http
            .get<Contacts[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * contactsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Contacts): Observable<Contacts> {
        return this.http
            .post<Contacts>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
