/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e9b968882f82d390e7778d0
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { ContactsService } from '../../services/contacts.service';
// Import Models
import { Contacts } from '../../domain/new-app_db/contacts';

// START - USED SERVICES
/**
* contactsService.create
*	@description CRUD ACTION create
*
* contactsService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* contactsService.get
*	@description CRUD ACTION get
*	@returns contacts
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Contacts
 */
@Component({
    selector: 'app-contacts-edit',
    templateUrl: 'contacts-edit.component.html',
    styleUrls: ['contacts-edit.component.css']
})
export class ContactsEditComponent implements OnInit {
    item: Contacts;
    model: Contacts;
    formValid: Boolean;

    constructor(
    private contactsService: ContactsService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Contacts();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.contactsService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Contacts
     *
     * @param {boolean} formValid Form validity check
     * @param Contacts item Contacts to save
     */
    save(formValid: boolean, item: Contacts): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.contactsService.update(item).subscribe(data => this.goBack());
            } else {
                this.contactsService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



